### ISSUE TITLE
As a client, I want to be able to see and manage my accounts balance

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#10]
## Tasks

- [x] Frontend: Dashboard page with account transactions (purchases, deposit with status and balance)
- [x] Frontend: Deposit form
- [x] Backend: schema redesign
- [x] Backend: account_transaction_deposit, (for later: account_transaction_withdraw)
- [x] Point of sale: UserAccountPurchase UI and backend
- [x] Manual testing

### Normal

1 Login and see a dashboard of transactions and balance
2 Add credit thought pix (send timestamp/value for canteen manual validation)
3 See state of credit request (awaiting approval, approved)

### Extension

2.1 Timestamp or value are invalid

## Related

* #46

## What I actually did

* Schema Redesign around generic_transactions
* Implementation of types of transactions: Regular and User-Account Purhcase, User Recharge and Canteen Withdraw. Just canteen_withdraw isnt avaliable in the frontend, but is working in the backend.
* User Recharge feature of pending transaction, which can be accepted or refused. Working in frontend already.
