### ISSUE TITLE
As a future canteen owner, I want to understand the app features and register a new canteen

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#13]
# Tasks

- [ ] ~~page: public landing page~~
- [x] page: public register/login
  - [x] User register validation
- [ ] ~~page: user dashboard~~
- [x] register functionality that creates a new canteen
  - [x] schema redefinition
  - [x] btns/page to create canteen
  - [x] DB: Include depency to a canteen to transaction, products, etc
  - [x] Register canteen (with server-side validation)
  
# Related

* #38 
* #37
