### ISSUE TITLE
As a future canteen client, I want to understand how the app works and register myself to a canteen I know

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#14]
## Tasks

- [x] Form: register client page
- [x] Page: placeholder dashboard for clients (main and dependents tabs)
- [x] Frontend: create routes and acess control restricitons
- [x] Backend: validate data and register user to canteen
- [x] Manual test of use case

### Normal

1 Acess the register page from the index
2 Register using an acess code given by the canteen
3 Acess the user dashboard

### Extensions

2.1 The acess code is invalid or doesn't exist

## Related

* #41
* #40
