### ISSUE TITLE
As an owner, I want to be able to register new employees

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#28]
## Tasks

- [x] Page: Manage Employee index (with remove and update inline btns)
- [x] Page: Add Employee/Update Employee
- [x] DB Read: display_role_options and display_employee_list
- [x] DB Create/update: register_employee, delete_employee, update_employee_role
- [x] Manual Test Use Case

### Normal

1. Login as owner and go to Manage Employees page
2. Add an employee with temporary password, basic info and a role
3. Change employee role
4. Soft delete an employee

### Extensions

1.1 Login as anything else won't allow to see Manage Employees page
2.1 Raise error if (a) form data is invalid (b) User or e-mail are already taken
3.1 Raise error if form data is invalid
3.2 Can't modify employee's info

## Related

* #39
