### ISSUE TITLE
As a client, I want to be able to register new dependents

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#29]
## Tasks

- [x] Create Manage Client page with fake data
- [x] Schema redesign
  - [x] Add new table user_child to keep track of special info about them
  - [x] Add Create/update/remove function to the new table
- [x] Add view to Manage Client's page with sample user_child data from db
- [x] Bind Create/Update/Delete to the page
- [x] Manual test use case

### Normal

1 Log in and go to Manage Dependents
2 See dependents and register a new one
3 Update some data about dependents

### Extension

2.1 Form data is invalid
3.1 Form data is invalid

## Related

* #44
* #45
