### ISSUE TITLE
As a manager, I want to be able to add, remove and update products and products categories

### ISSUE THREAD

**Issue by pedro-psb** [pedro-psb/pypos-canteen#8]
## Tasks

Product Management Frontend
- [x] Page: add_category
- [x] Page: add_product
- [x] Page: update_category
- [x] Page: update_product
- [x] Backend bind

Add to new issue(s):
- [x] Feature(frontend): 'category_add' with popover (so user dont need to exit the page)
- [x] Bug(frontend): make left sidebar fixed
- [x] Bug(update/add category/product): entities that were deactivated don't let new entities use their names (name has UNIQUE constrain).When adding a new entity, if the name is used by an unactive entity, the old entity is reactivated instead of creating a new one. When updating an existing entity, the old entity should be reactivated and all current entity products belonging to them should be moved to the old reactivated entity.

### Product

* login as owner/manager and:
  * add a product
    * optional photo and category
    * required name and price
  * update an existing product
  * delete an existing product

### Category

* login as owner/manager and:
  * add a category
    * required name
  * update an existing category
  * delete an existing category
